export const TestimonialData = [
  {
    text: "They offered us great suggestions and helped us build our brand with website content and strategies. Highly recommended !",
    profile: "/assets/prayoga.png",
    name: "Rauf Chippa",
    stars: 5,
    designation1: "Co-Founder,",
    designation2: "Prayoga Films, Ahmedabad",
  },
  {
    text: "Consistently exceeds our expectations as a content partner, delivering top-notch content marketing and branding skills.",
    profile: "/assets/leo92.png",
    name: "Himanshu Sawant",
    stars: 5,
    designation1: "Brand Experience Manager,",
    designation2: "Leo9 Studio",
  },
  {
    text: "Their professional and creative team provided great support throughout the project.",
    profile: "/trusted/Mount_Magica.jpg",
    name: "Arpit Kumar",
    stars: 5,
    designation1: "Founder & MD,",
    designation2: "Mount Magica, Ranchi",
  },
  {
    text: "Team Squirrels transformed our brand into a powerful force. Their logo design and brand identity perfectly capture our vision.",
    profile: "/trusted/Recuro.png",
    name: "John",
    stars: 5,
    designation1: "Director of Marketing,",
    designation2: "Recuro Health, USA",
  },
  {
    text: "We've seen a significant ROI from our marketing campaigns with Squirrels. Their data-driven approach & strategies have helped us expand our market share.",
    profile: "/trusted/Costalcitydental.png",
    name: "Sunny Singh",
    stars: 5,
    designation1: "Sales & Marketing Head,",
    designation2: "Costal City Dental, Vancouver, CA",
  },
  {
    text: "The team at Squirrels provided exceptional support, from developing our brand message to effective campaigns. We recommend them for all real-estate projects.",
    profile: "/trusted/Jannatproperties.png",
    name: "Alhamza Mumtaz",
    stars: 5,
    designation1: "Director Marketing, Jannat",
    designation2: "Properties, Dhahran, Saudi Arabia",
  },
  {
    text: "We were particularly impressed with Team Squirrel's attention to detail and commitment to user experience. Our website is now a valuable asset for our business.",
    profile: "/trusted/Silausa.png",
    name: "Sumit Baghel",
    stars: 5,
    designation1: "Chief Engineer (Product)",
    designation2: "Sila HQ, USA",
  },
  {
    text: "Squirrel's marketing campaigns have driven huge traffic to our website and increased sales too. Their expertise in social media advertising and content creation is unparalleled.",
    profile: "/trusted/Jennifer.png",
    name: "Robert",
    stars: 5,
    designation1: "President & CMO, Jennifer &",
    designation2: "Linda Shipping Co, USA",
  },
  {
    text: "In Canada, we sought a marketing partner who could help us expand our online presence. Team Squirrel's social media campaigns & SEO strategies have connect us to our TG.",
    profile: "/trusted/Voiceflow.png",
    name: "Liam",
    stars: 5,
    designation1: "Marketing Manager,",
    designation2: "Voiceflow, Canada",
  }
];
